export const routePermissions: Record<string, string> = {
  "/app": "dashboard.view",
  "/app/assistant-ia": "assistant.use",
  "/ventes": "ventes.view",
  "/devis": "ventes.view",
  "/clients": "parties.access",
  "/services": "ventes.view",
  "/categories": "ventes.view",
  "/stock": "ventes.view",
  "/achats": "achats.view",
  "/fournisseurs": "parties.access",
  "/depenses": "ventes.view",
  "/parametres": "settings.manage",
  "/settings/catalogue": "settings.manage",
  "/settings/users": "settings.manage",
  "/utilisateurs": "settings.manage",
};
