export const routePermissions: Record<string, string> = {
  "/app": "dashboard.view",
  "/app/assistant-ia": "assistant.use",
  "/ventes": "ventes.view",
  "/devis": "ventes.view",
  "/clients": "parties.access",
  "/services": "ventes.view",
  "/categories": "ventes.view",
  "/stock": "ventes.view",
  "/achats": "achats.view",
  "/fournisseurs": "parties.access",
  "/depenses": "ventes.view",
  "/parametres": "settings.manage",
  "/settings/catalogue": "settings.manage",
  "/settings/users": "settings.manage",
  "/utilisateurs": "settings.manage",
  "/hotel": "hotel.reservations.view",
  "/hotel/reservations": "hotel.reservations.view",
  "/hotel/rooms": "hotel.rooms.view",
  "/hotel/logements": "hotel.rooms.view",
  "/hotel/guests": "hotel.guests.view",
  "/hotel/voyageurs": "hotel.guests.view",
  "/hotel/expenses": "hotel.expenses.view",
  "/hotel/reports": "hotel.reports.view",
  "/hotel/rapports": "hotel.reports.view",
  "/hotel/settings": "hotel.settings.view",
  "/hotel/parametres": "hotel.settings.view",
};
