import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AppShell } from "@/components/mms/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { useTenant } from "@/providers/TenantProvider";
import { formatCurrency,formatDate } from "@/lib/mms/format";
import { toast } from "sonner";
import { hotelStayTotals } from "@/lib/hotel-calculations";
const db=supabase as any;

export function HotelReservationsPage(){const qc=useQueryClient();const {profile}=useTenant();const [form,setForm]=useState({guest_id:"",room_id:"",check_in:"",check_out:"",nightly_rate:"",discount:"0",status:"confirmed"});
 const {data}=useQuery({queryKey:["hotel-reservations"],queryFn:async()=>{const [r,g,rooms]=await Promise.all([db.from("hotel_reservation_balances").select("*").order("check_in",{ascending:false}),db.from("hotel_guests").select("id,first_name,last_name"),db.from("hotel_rooms").select("id,number,rate,status")]);for(const x of [r,g,rooms])if(x.error)throw x.error;return {reservations:r.data??[],guests:g.data??[],rooms:rooms.data??[]}}});
 const save=useMutation({mutationFn:async()=>{if(!profile?.tenant_id)throw new Error("Tenant introuvable");const {error}=await db.from("hotel_reservations").insert({...form,tenant_id:profile.tenant_id,nightly_rate:Number(form.nightly_rate),discount:Number(form.discount)});if(error)throw error},onSuccess:()=>{toast.success("Réservation créée");setForm({guest_id:"",room_id:"",check_in:"",check_out:"",nightly_rate:"",discount:"0",status:"confirmed"});qc.invalidateQueries({queryKey:["hotel-reservations"]});qc.invalidateQueries({queryKey:["hotel-overview"]})},onError:(e:Error)=>toast.error(e.message.includes("hotel_reservations_no_overlap")?"Ce logement est déjà réservé sur cette période.":e.message)});
 const {nights,grandTotal:total}=hotelStayTotals(form.check_in,form.check_out,Number(form.nightly_rate||0),Number(form.discount||0));
 return <AppShell title="Réservations" subtitle="Séjours, paiements, extras et soldes"><div className="mb-6 grid gap-3 rounded-xl border p-4 md:grid-cols-4"><div><Label>Voyageur</Label><Select value={form.guest_id} onValueChange={v=>setForm({...form,guest_id:v})}><SelectTrigger><SelectValue placeholder="Sélectionner"/></SelectTrigger><SelectContent>{data?.guests.map((g:any)=><SelectItem key={g.id} value={g.id}>{g.first_name} {g.last_name}</SelectItem>)}</SelectContent></Select></div><div><Label>Logement</Label><Select value={form.room_id} onValueChange={v=>{const room=data?.rooms.find((r:any)=>r.id===v);setForm({...form,room_id:v,nightly_rate:String(room?.rate??"")})}}><SelectTrigger><SelectValue placeholder="Sélectionner"/></SelectTrigger><SelectContent>{data?.rooms.map((r:any)=><SelectItem key={r.id} value={r.id}>N° {r.number}</SelectItem>)}</SelectContent></Select></div><div><Label>Arrivée</Label><Input type="date" value={form.check_in} onChange={e=>setForm({...form,check_in:e.target.value})}/></div><div><Label>Départ</Label><Input type="date" value={form.check_out} onChange={e=>setForm({...form,check_out:e.target.value})}/></div><div><Label>Tarif / nuit</Label><Input type="number" min="0" value={form.nightly_rate} onChange={e=>setForm({...form,nightly_rate:e.target.value})}/></div><div><Label>Remise</Label><Input type="number" min="0" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value})}/></div><div className="flex items-end text-sm"><b>{nights} nuit(s) · {formatCurrency(total)}</b></div><div className="flex items-end"><Button className="w-full" disabled={save.isPending||!form.guest_id||!form.room_id||nights<1} onClick={()=>save.mutate()}>{save.isPending?"Création…":"Créer"}</Button></div></div><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-left">Séjour</th><th>Statut</th><th>Nuits</th><th>Total</th><th>Payé</th><th>Solde</th></tr></thead><tbody>{data?.reservations.map((r:any)=><tr key={r.id} className="border-b"><td className="p-3">{formatDate(r.check_in)} → {formatDate(r.check_out)}</td><td className="text-center">{r.status}</td><td className="text-center">{r.nights}</td><td className="text-center">{formatCurrency(Number(r.grand_total))}</td><td className="text-center">{formatCurrency(Number(r.paid_total))}</td><td className="text-center font-medium">{formatCurrency(Number(r.balance_due))}</td></tr>)}</tbody></table></div></AppShell>}
