import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, Loader2, MessageCircle, Pencil, Phone, Plus, RotateCcw, Search, Wrench } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/mms/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { usePermissions } from "@/hooks/use-permissions";
import { supabase } from "@/integrations/supabase/client";
import { useTenant } from "@/providers/TenantProvider";

const TRADES = ["Plombier","Électricien","Climaticien","Menuisier","Serrurier","Peintre","Maçon","Carreleur","Technicien électroménager","Technicien Internet","Technicien télévision","Pisciniste","Jardinier","Agent d’entretien","Autre"] as const;
const AVAILABILITY = { available: ["Disponible","bg-emerald-50 text-emerald-700"], busy: ["Occupé","bg-amber-50 text-amber-700"], unavailable: ["Indisponible","bg-slate-100 text-slate-600"] } as const;
type Availability = keyof typeof AVAILABILITY;
type Provider = { id:string; tenant_id:string; full_name:string; company_name:string|null; trade:string; phone:string; whatsapp:string|null; intervention_area:string|null; availability_status:Availability; internal_note:string|null; is_active:boolean; created_at:string; updated_at:string };
type ProviderForm = Omit<Provider,"id"|"tenant_id"|"created_at"|"updated_at"|"is_active">;
const EMPTY: ProviderForm = { full_name:"", company_name:"", trade:"Plombier", phone:"", whatsapp:"", intervention_area:"", availability_status:"available", internal_note:"" };
const cleanPhone = (value:string) => value.replace(/\D/g, "");
const errorMessage = (error:unknown) => (error as {message?:string})?.message || "Une erreur inattendue est survenue.";
const db = supabase;

export function HotelProvidersPage() {
  const { profile, loading: tenantLoading } = useTenant();
  const permissions = usePermissions();
  const qc = useQueryClient();
  const tenantId = profile?.tenant_id;
  const codes = permissions.data?.permissions ?? [];
  const admin = permissions.data?.role === "Administrateur";
  const canCreate = admin || codes.includes("hotel.maintenance.create");
  const canUpdate = admin || codes.includes("hotel.maintenance.update");
  const [search,setSearch] = useState(""); const [trade,setTrade] = useState("all"); const [availability,setAvailability] = useState("all"); const [active,setActive] = useState("active");
  const [editor,setEditor] = useState<Provider|null|undefined>(undefined); const [details,setDetails] = useState<Provider|null>(null);
  const query = useQuery({ queryKey:["hotel_maintenance_providers",tenantId], enabled:!tenantLoading && Boolean(tenantId), queryFn:async()=>{ if(!tenantId) throw new Error("Établissement introuvable."); const {data,error}=await db.from("hotel_maintenance_providers").select("*").eq("tenant_id",tenantId).order("full_name"); if(error) throw error; return data as Provider[]; } });
  const filtered = useMemo(()=>{ const needle=search.trim().toLocaleLowerCase("fr"); return (query.data??[]).filter(p=>{ const hay=[p.full_name,p.company_name,p.phone,p.whatsapp,p.trade,p.intervention_area].filter(Boolean).join(" ").toLocaleLowerCase("fr"); return (!needle||hay.includes(needle))&&(trade==="all"||p.trade===trade)&&(availability==="all"||p.availability_status===availability)&&(active==="all"||(active==="active")===p.is_active); }); },[query.data,search,trade,availability,active]);
  const save = useMutation({ mutationFn:async(form:ProviderForm & {id?:string})=>{ if(!tenantId) throw new Error("Établissement introuvable."); const payload={...form,tenant_id:tenantId,company_name:form.company_name?.trim()||null,whatsapp:form.whatsapp?.trim()||null,intervention_area:form.intervention_area?.trim()||null,internal_note:form.internal_note?.trim()||null}; const result=form.id?await db.from("hotel_maintenance_providers").update(payload).eq("tenant_id",tenantId).eq("id",form.id):await db.from("hotel_maintenance_providers").insert(payload); if(result.error) throw result.error; }, onSuccess:()=>{setEditor(undefined);void qc.invalidateQueries({queryKey:["hotel_maintenance_providers",tenantId]});toast.success("Prestataire enregistré");},onError:e=>toast.error(errorMessage(e)) });
  const remove = useMutation({ mutationFn:async(p:Provider)=>{ if(!tenantId) throw new Error("Établissement introuvable."); const {error}=await db.from("hotel_maintenance_providers").delete().eq("tenant_id",tenantId).eq("id",p.id);if(error)throw error;},onSuccess:async()=>{await qc.invalidateQueries({queryKey:["hotel_maintenance_providers",tenantId]});toast.success("Prestataire supprimé");},onError:e=>toast.error(errorMessage(e))});
  const reset=()=>{setSearch("");setTrade("all");setAvailability("all");setActive("active");};
  return <AppShell title="Prestataires & professionnels" subtitle="Trouvez rapidement un professionnel par métier" actions={canCreate?<Button className="gap-2 bg-[#C9A227] text-[#0F172A] hover:bg-[#B89120]" onClick={()=>setEditor(null)}><Plus className="size-4"/><span className="hidden sm:inline">Ajouter un prestataire</span><span className="sm:hidden">Ajouter</span></Button>:undefined}>
    <div className="mx-auto max-w-7xl space-y-5">
      <section className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-[#0F172A] md:grid-cols-[minmax(240px,1fr)_repeat(3,180px)_auto]">
        <div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom, entreprise, téléphone, métier ou zone" aria-label="Rechercher un prestataire"/></div>
        <Select value={trade} onChange={setTrade} label="Métier"><option value="all">Tous les métiers</option>{TRADES.map(v=><option key={v}>{v}</option>)}</Select>
        <Select value={availability} onChange={setAvailability} label="Disponibilité"><option value="all">Toutes disponibilités</option>{Object.entries(AVAILABILITY).map(([v,m])=><option key={v} value={v}>{m[0]}</option>)}</Select>
        <Select value={active} onChange={setActive} label="Statut"><option value="all">Tous les statuts</option><option value="active">Actifs</option><option value="inactive">Inactifs</option></Select>
        <Button variant="outline" className="gap-2" onClick={reset}><RotateCcw className="size-4"/>Effacer</Button>
      </section>
      {query.isLoading?<State icon={<Loader2 className="size-6 animate-spin"/>} text="Chargement des prestataires…"/>:query.error?<State text={errorMessage(query.error)}/>:filtered.length===0?<State icon={<Wrench className="size-7"/>} text="Aucun prestataire ne correspond à votre recherche."/>:<>
        <div className="hidden overflow-hidden rounded-2xl border bg-white shadow-sm dark:bg-[#0F172A] md:block"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500 dark:bg-white/5"><tr>{["Prestataire","Métier","Contact","Zone","Disponibilité","Note interne","Statut","Actions"].map(h=><th key={h} className="px-3 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(p=><ProviderRow key={p.id} provider={p} canUpdate={canUpdate} pending={remove.isPending} onDetails={setDetails} onEdit={p=>setEditor(p)} onDelete={p=>remove.mutate(p)}/>)}</tbody></table></div>
        <div className="grid gap-3 md:hidden">{filtered.map(p=><ProviderCard key={p.id} provider={p} canUpdate={canUpdate} pending={remove.isPending} onDetails={setDetails} onEdit={p=>setEditor(p)} onDelete={p=>remove.mutate(p)}/>)}</div>
      </>}
      <p className="text-xs text-muted-foreground">{filtered.length} prestataire{filtered.length!==1?"s":""} affiché{filtered.length!==1?"s":""}</p>
    </div>
    <ProviderEditor open={editor!==undefined} provider={editor??null} pending={save.isPending} onClose={()=>setEditor(undefined)} onSave={v=>save.mutate(v)}/>
    <ProviderDetails provider={details} onClose={()=>setDetails(null)}/>
  </AppShell>;
}

function Select({value,onChange,label,children}:{value:string;onChange:(v:string)=>void;label:string;children:React.ReactNode}) { return <select aria-label={label} value={value} onChange={e=>onChange(e.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm">{children}</select>; }
function AvailabilityBadge({value}:{value:Availability}) { const meta=AVAILABILITY[value]??AVAILABILITY.unavailable; return <Badge className={`${meta[1]} border-0`}>{meta[0]}</Badge>; }
function ContactButtons({provider}:{provider:Provider}) { const wa=cleanPhone(provider.whatsapp||provider.phone); return <div className="flex gap-1"><Button asChild size="sm" variant="outline" className="h-8 gap-1"><a href={`tel:${provider.phone}`} aria-label={`Appeler ${provider.full_name}`}><Phone className="size-3.5"/><span className="hidden xl:inline">Appeler</span></a></Button><Button asChild size="sm" className="h-8 gap-1 bg-emerald-600 hover:bg-emerald-700"><a href={`https://wa.me/${wa}`} target="_blank" rel="noreferrer" aria-label={`WhatsApp ${provider.full_name}`}><MessageCircle className="size-3.5"/><span className="hidden xl:inline">WhatsApp</span></a></Button></div>; }
type Actions={provider:Provider;canUpdate:boolean;pending:boolean;onDetails:(p:Provider)=>void;onEdit:(p:Provider)=>void;onDelete:(p:Provider)=>void};
function MoreActions({provider:p,canUpdate,pending,onDetails,onEdit,onDelete}:Actions){return <div className="flex flex-wrap gap-1"><Button size="icon" variant="ghost" className="size-8" title="Voir la fiche" onClick={()=>onDetails(p)}><Eye className="size-4"/></Button>{canUpdate&&<Button size="icon" variant="ghost" className="size-8" title="Modifier" onClick={()=>onEdit(p)}><Pencil className="size-4"/></Button>}{canUpdate&&<Button size="sm" variant="ghost" className="h-8 text-xs text-destructive" disabled={pending} onClick={()=>onDelete(p)}>Supprimer</Button>}</div>}
function ProviderRow(props:Actions){const p=props.provider;return <tr className="align-top hover:bg-slate-50/70 dark:hover:bg-white/5"><td className="px-3 py-3"><div className="font-semibold text-[#102A43] dark:text-white">{p.full_name}</div><div className="text-xs text-muted-foreground">{p.company_name||"Indépendant"}</div></td><td className="px-3 py-3"><Badge variant="outline" className="border-[#C9A227]/40 text-[#806518]">{p.trade}</Badge></td><td className="px-3 py-3"><div className="mb-1 text-xs">{p.phone}</div><ContactButtons provider={p}/></td><td className="px-3 py-3 text-muted-foreground">{p.intervention_area||"—"}</td><td className="px-3 py-3"><AvailabilityBadge value={p.availability_status}/></td><td className="max-w-40 truncate px-3 py-3 text-muted-foreground" title={p.internal_note||""}>{p.internal_note||"—"}</td><td className="px-3 py-3"><Badge variant={p.is_active?"default":"secondary"}>{p.is_active?"Actif":"Inactif"}</Badge></td><td className="px-3 py-3"><MoreActions {...props}/></td></tr>}
function ProviderCard(props:Actions){const p=props.provider;return <article className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-[#0F172A]"><div className="flex items-start justify-between gap-2"><div><h2 className="font-semibold text-[#102A43] dark:text-white">{p.full_name}</h2><p className="text-xs text-muted-foreground">{p.company_name||"Indépendant"} · {p.intervention_area||"Zone non renseignée"}</p></div><Badge variant={p.is_active?"default":"secondary"}>{p.is_active?"Actif":"Inactif"}</Badge></div><div className="my-3 flex flex-wrap gap-2"><Badge variant="outline" className="border-[#C9A227]/40 text-[#806518]">{p.trade}</Badge><AvailabilityBadge value={p.availability_status}/></div><p className="mb-3 text-sm">{p.phone}</p><div className="flex items-center justify-between gap-2 border-t pt-3"><ContactButtons provider={p}/><MoreActions {...props}/></div></article>}
function State({icon,text}:{icon?:React.ReactNode;text:string}){return <div className="flex min-h-48 flex-col items-center justify-center gap-3 rounded-2xl border border-dashed bg-white p-8 text-center text-sm text-muted-foreground dark:bg-[#0F172A]">{icon}{text}</div>}

function ProviderEditor({open,provider,pending,onClose,onSave}:{open:boolean;provider:Provider|null;pending:boolean;onClose:()=>void;onSave:(v:ProviderForm&{id?:string})=>void}){const [form,setForm]=useState<ProviderForm>(EMPTY);const identity=provider?.id??"new";return <Dialog open={open} onOpenChange={v=>!pending&&!v&&onClose()}><DialogContent key={identity} className="max-h-[90vh] overflow-y-auto sm:max-w-2xl" onOpenAutoFocus={()=>setForm(provider?{full_name:provider.full_name,company_name:provider.company_name,trade:provider.trade,phone:provider.phone,whatsapp:provider.whatsapp,intervention_area:provider.intervention_area,availability_status:provider.availability_status,internal_note:provider.internal_note}:EMPTY)}><DialogHeader><DialogTitle>{provider?"Modifier le prestataire":"Ajouter un prestataire"}</DialogTitle><DialogDescription>Coordonnées et informations utiles aux équipes de l’hôtel.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label="Nom complet *"><Input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></Field><Field label="Entreprise"><Input value={form.company_name??""} onChange={e=>setForm({...form,company_name:e.target.value})}/></Field><Field label="Métier *"><Select value={form.trade} onChange={v=>setForm({...form,trade:v})} label="Métier">{TRADES.map(v=><option key={v}>{v}</option>)}</Select></Field><Field label="Disponibilité"><Select value={form.availability_status} onChange={v=>setForm({...form,availability_status:v as Availability})} label="Disponibilité">{Object.entries(AVAILABILITY).map(([v,m])=><option value={v} key={v}>{m[0]}</option>)}</Select></Field><Field label="Téléphone *"><Input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="WhatsApp"><Input type="tel" value={form.whatsapp??""} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></Field><Field label="Zone d’intervention"><Input value={form.intervention_area??""} onChange={e=>setForm({...form,intervention_area:e.target.value})}/></Field><div className="sm:col-span-2"><Field label="Note interne"><Textarea rows={3} value={form.internal_note??""} onChange={e=>setForm({...form,internal_note:e.target.value})}/></Field></div></div><DialogFooter><Button variant="outline" disabled={pending} onClick={onClose}>Annuler</Button><Button disabled={pending||!form.full_name.trim()||!form.phone.trim()} onClick={()=>onSave({...form,...(provider?{id:provider.id}:{})})}>{pending&&<Loader2 className="mr-2 size-4 animate-spin"/>}Enregistrer</Button></DialogFooter></DialogContent></Dialog>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function ProviderDetails({provider,onClose}:{provider:Provider|null;onClose:()=>void}){return <Dialog open={Boolean(provider)} onOpenChange={v=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>{provider?.full_name}</DialogTitle><DialogDescription>{provider?.company_name||"Prestataire indépendant"}</DialogDescription></DialogHeader>{provider&&<div className="grid grid-cols-2 gap-4 text-sm"><Detail label="Métier" value={provider.trade}/><Detail label="Disponibilité" value={AVAILABILITY[provider.availability_status][0]}/><Detail label="Téléphone" value={provider.phone}/><Detail label="WhatsApp" value={provider.whatsapp||"—"}/><Detail label="Zone" value={provider.intervention_area||"—"}/><div className="col-span-2"><Detail label="Note interne" value={provider.internal_note||"—"}/></div><div className="col-span-2"><ContactButtons provider={provider}/></div></div>}</DialogContent></Dialog>}
function Detail({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>}
