// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Reads an env var from every plausible source, in order of preference:
// 1. import.meta.env (Vite client/SSR build-time replacement) — normal path
// 2. process.env, guarded: in a browser or Workers runtime `process` may not
//    exist at all, and referencing `process.env.X` unguarded would throw a
//    ReferenceError instead of the intended "missing env var" message.
function readEnvVar(...names: string[]): string | undefined {
  const importMetaEnv = (import.meta as unknown as { env?: Record<string, string | undefined> })
    .env;
  for (const name of names) {
    const value = importMetaEnv?.[name];
    if (value) return value;
  }
  if (typeof process !== "undefined" && process?.env) {
    for (const name of names) {
      const value = process.env[name];
      if (value) return value;
    }
  }
  return undefined;
}

function createSupabaseClient() {
  // Prefer the VITE_-prefixed vars (build-time injected for client/SSR).
  // Fall back to the unprefixed names in case they were set directly in the
  // runtime environment (e.g. a Node/SSR host that loads .env into
  // process.env under the unprefixed names).
  const SUPABASE_URL = readEnvVar("VITE_SUPABASE_URL", "SUPABASE_URL");
  const SUPABASE_PUBLISHABLE_KEY = readEnvVar(
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_PUBLISHABLE_KEY",
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
