export const analyticsEvents = {
  pageview: "$pageview",
  moduleOpened: "module_opened",
  userSignedIn: "user_signed_in",
  userSignedOut: "user_signed_out",
  frontendError: "frontend_error",
  quoteCreated: "quote_created",
  quoteUpdated: "quote_updated",
  quoteDeleted: "quote_deleted",
  quoteSent: "quote_sent",
  quoteAccepted: "quote_accepted",
  quotePaymentRecorded: "quote_payment_recorded",
  invoiceCreated: "invoice_created",
  invoiceUpdated: "invoice_updated",
  invoiceSent: "invoice_sent",
  invoicePaymentRecorded: "invoice_payment_recorded",
  saleCreated: "sale_created",
  saleCompleted: "sale_completed",
  saleCancelled: "sale_cancelled",
  hotelReservationCreated: "hotel_reservation_created",
  hotelReservationUpdated: "hotel_reservation_updated",
  hotelCheckinCompleted: "hotel_checkin_completed",
  hotelCheckoutCompleted: "hotel_checkout_completed",
  hotelPaymentRecorded: "hotel_payment_recorded",
  hotelInvoiceCreated: "hotel_invoice_created",
  hotelInvoiceUpdated: "hotel_invoice_updated",
  hotelInvoiceSent: "hotel_invoice_sent",
  hotelInvoicePaymentRecorded: "hotel_invoice_payment_recorded",
  createQuoteClicked: "create_quote_clicked",
  createInvoiceClicked: "create_invoice_clicked",
  newSaleClicked: "new_sale_clicked",
} as const;

export type AnalyticsEventName = (typeof analyticsEvents)[keyof typeof analyticsEvents];
