/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R403RouteImport } from './routes/403'
import { Route as AbonnementExpireRouteImport } from './routes/abonnement-expire'
import { Route as AchatsRouteImport } from './routes/achats'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DemandeEnAttenteRouteImport } from './routes/demande-en-attente'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as EssaiGratuitRouteImport } from './routes/essai-gratuit'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LicenceRouteImport } from './routes/licence'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PartnerAdminRouteImport } from './routes/partner-admin'
import { Route as PartnerLoginRouteImport } from './routes/partner-login'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as VentesRouteImport } from './routes/ventes'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as AppAssistantIaRouteImport } from './routes/app.assistant-ia'
import { Route as HotelIndexRouteImport } from './routes/hotel.index'
import { Route as HotelCalendrierRouteImport } from './routes/hotel.calendrier'
import { Route as HotelChambresRouteImport } from './routes/hotel.chambres'
import { Route as HotelLogementsRouteImport } from './routes/hotel.logements'
import { Route as HotelParametresRouteImport } from './routes/hotel.parametres'
import { Route as HotelPrestatairesRouteImport } from './routes/hotel.prestataires'
import { Route as HotelRapportsRouteImport } from './routes/hotel.rapports'
import { Route as HotelReservationsRouteImport } from './routes/hotel.reservations'
import { Route as HotelSmsRouteImport } from './routes/hotel.sms'
import { Route as HotelVoyageursRouteImport } from './routes/hotel.voyageurs'
import { Route as LoginSlugRouteImport } from './routes/login_.$slug'
import { Route as SettingsCatalogueRouteImport } from './routes/settings.catalogue'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SuperAdminIaPlatformRouteImport } from './routes/super-admin.ia-platform'
import { Route as SuperAdminModulesRouteImport } from './routes/super-admin.modules'
import { Route as SuperAdminPartnersRouteImport } from './routes/super-admin.partners'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementExpireRoute = AbonnementExpireRouteImport.update({
  id: '/abonnement-expire',
  path: '/abonnement-expire',
  getParentRoute: () => rootRouteImport,
} as any)
const AchatsRoute = AchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandeEnAttenteRoute = DemandeEnAttenteRouteImport.update({
  id: '/demande-en-attente',
  path: '/demande-en-attente',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaiGratuitRoute = EssaiGratuitRouteImport.update({
  id: '/essai-gratuit',
  path: '/essai-gratuit',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenceRoute = LicenceRouteImport.update({
  id: '/licence',
  path: '/licence',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAdminRoute = PartnerAdminRouteImport.update({
  id: '/partner-admin',
  path: '/partner-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/partner-login',
  path: '/partner-login',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const VentesRoute = VentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/app/$',
  path: '/app/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssistantIaRoute = AppAssistantIaRouteImport.update({
  id: '/app/assistant-ia',
  path: '/app/assistant-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelIndexRoute = HotelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HotelRoute,
} as any)
const HotelCalendrierRoute = HotelCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => HotelRoute,
} as any)
const HotelChambresRoute = HotelChambresRouteImport.update({
  id: '/chambres',
  path: '/chambres',
  getParentRoute: () => HotelRoute,
} as any)
const HotelLogementsRoute = HotelLogementsRouteImport.update({
  id: '/logements',
  path: '/logements',
  getParentRoute: () => HotelRoute,
} as any)
const HotelParametresRoute = HotelParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => HotelRoute,
} as any)
const HotelPrestatairesRoute = HotelPrestatairesRouteImport.update({
  id: '/prestataires',
  path: '/prestataires',
  getParentRoute: () => HotelRoute,
} as any)
const HotelRapportsRoute = HotelRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => HotelRoute,
} as any)
const HotelReservationsRoute = HotelReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => HotelRoute,
} as any)
const HotelSmsRoute = HotelSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => HotelRoute,
} as any)
const HotelVoyageursRoute = HotelVoyageursRouteImport.update({
  id: '/voyageurs',
  path: '/voyageurs',
  getParentRoute: () => HotelRoute,
} as any)
const LoginSlugRoute = LoginSlugRouteImport.update({
  id: '/login_/$slug',
  path: '/login/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCatalogueRoute = SettingsCatalogueRouteImport.update({
  id: '/settings/catalogue',
  path: '/settings/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIaPlatformRoute = SuperAdminIaPlatformRouteImport.update({
  id: '/ia-platform',
  path: '/ia-platform',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminModulesRoute = SuperAdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPartnersRoute = SuperAdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/abonnement-expire': typeof AbonnementExpireRoute
  '/achats': typeof AchatsRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/demande-en-attente': typeof DemandeEnAttenteRoute
  '/demo': typeof DemoRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/essai-gratuit': typeof EssaiGratuitRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fournisseurs': typeof FournisseursRoute
  '/hotel': typeof HotelRouteWithChildren
  '/journal': typeof JournalRoute
  '/licence': typeof LicenceRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/partner': typeof PartnerRoute
  '/partner-admin': typeof PartnerAdminRoute
  '/partner-login': typeof PartnerLoginRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/stock': typeof StockRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
  '/app/$': typeof AppSplatRoute
  '/app/assistant-ia': typeof AppAssistantIaRoute
  '/hotel/calendrier': typeof HotelCalendrierRoute
  '/hotel/chambres': typeof HotelChambresRoute
  '/hotel/logements': typeof HotelLogementsRoute
  '/hotel/parametres': typeof HotelParametresRoute
  '/hotel/prestataires': typeof HotelPrestatairesRoute
  '/hotel/rapports': typeof HotelRapportsRoute
  '/hotel/reservations': typeof HotelReservationsRoute
  '/hotel/sms': typeof HotelSmsRoute
  '/hotel/voyageurs': typeof HotelVoyageursRoute
  '/login/$slug': typeof LoginSlugRoute
  '/settings/catalogue': typeof SettingsCatalogueRoute
  '/settings/users': typeof SettingsUsersRoute
  '/super-admin/ia-platform': typeof SuperAdminIaPlatformRoute
  '/super-admin/modules': typeof SuperAdminModulesRoute
  '/super-admin/partners': typeof SuperAdminPartnersRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/app/': typeof AppIndexRoute
  '/hotel/': typeof HotelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/abonnement-expire': typeof AbonnementExpireRoute
  '/achats': typeof AchatsRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/demande-en-attente': typeof DemandeEnAttenteRoute
  '/demo': typeof DemoRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/essai-gratuit': typeof EssaiGratuitRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fournisseurs': typeof FournisseursRoute
  '/journal': typeof JournalRoute
  '/licence': typeof LicenceRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/partner': typeof PartnerRoute
  '/partner-admin': typeof PartnerAdminRoute
  '/partner-login': typeof PartnerLoginRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/stock': typeof StockRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
  '/app/$': typeof AppSplatRoute
  '/app/assistant-ia': typeof AppAssistantIaRoute
  '/hotel/calendrier': typeof HotelCalendrierRoute
  '/hotel/chambres': typeof HotelChambresRoute
  '/hotel/logements': typeof HotelLogementsRoute
  '/hotel/parametres': typeof HotelParametresRoute
  '/hotel/prestataires': typeof HotelPrestatairesRoute
  '/hotel/rapports': typeof HotelRapportsRoute
  '/hotel/reservations': typeof HotelReservationsRoute
  '/hotel/sms': typeof HotelSmsRoute
  '/hotel/voyageurs': typeof HotelVoyageursRoute
  '/login/$slug': typeof LoginSlugRoute
  '/settings/catalogue': typeof SettingsCatalogueRoute
  '/settings/users': typeof SettingsUsersRoute
  '/super-admin/ia-platform': typeof SuperAdminIaPlatformRoute
  '/super-admin/modules': typeof SuperAdminModulesRoute
  '/super-admin/partners': typeof SuperAdminPartnersRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/app': typeof AppIndexRoute
  '/hotel': typeof HotelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/abonnement-expire': typeof AbonnementExpireRoute
  '/achats': typeof AchatsRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/demande-en-attente': typeof DemandeEnAttenteRoute
  '/demo': typeof DemoRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/essai-gratuit': typeof EssaiGratuitRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fournisseurs': typeof FournisseursRoute
  '/hotel': typeof HotelRouteWithChildren
  '/journal': typeof JournalRoute
  '/licence': typeof LicenceRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/partner': typeof PartnerRoute
  '/partner-admin': typeof PartnerAdminRoute
  '/partner-login': typeof PartnerLoginRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/stock': typeof StockRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
  '/app/$': typeof AppSplatRoute
  '/app/assistant-ia': typeof AppAssistantIaRoute
  '/hotel/calendrier': typeof HotelCalendrierRoute
  '/hotel/chambres': typeof HotelChambresRoute
  '/hotel/logements': typeof HotelLogementsRoute
  '/hotel/parametres': typeof HotelParametresRoute
  '/hotel/prestataires': typeof HotelPrestatairesRoute
  '/hotel/rapports': typeof HotelRapportsRoute
  '/hotel/reservations': typeof HotelReservationsRoute
  '/hotel/sms': typeof HotelSmsRoute
  '/hotel/voyageurs': typeof HotelVoyageursRoute
  '/login_/$slug': typeof LoginSlugRoute
  '/settings/catalogue': typeof SettingsCatalogueRoute
  '/settings/users': typeof SettingsUsersRoute
  '/super-admin/ia-platform': typeof SuperAdminIaPlatformRoute
  '/super-admin/modules': typeof SuperAdminModulesRoute
  '/super-admin/partners': typeof SuperAdminPartnersRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/app/': typeof AppIndexRoute
  '/hotel/': typeof HotelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/abonnement-expire'
    | '/achats'
    | '/categories'
    | '/clients'
    | '/demande-en-attente'
    | '/demo'
    | '/depenses'
    | '/devis'
    | '/essai-gratuit'
    | '/fonctionnalites'
    | '/forgot-password'
    | '/fournisseurs'
    | '/hotel'
    | '/journal'
    | '/licence'
    | '/login'
    | '/parametres'
    | '/partner'
    | '/partner-admin'
    | '/partner-login'
    | '/rapports'
    | '/reset-password'
    | '/services'
    | '/stock'
    | '/super-admin'
    | '/tarifs'
    | '/utilisateurs'
    | '/ventes'
    | '/app/$'
    | '/app/assistant-ia'
    | '/hotel/calendrier'
    | '/hotel/chambres'
    | '/hotel/logements'
    | '/hotel/parametres'
    | '/hotel/prestataires'
    | '/hotel/rapports'
    | '/hotel/reservations'
    | '/hotel/sms'
    | '/hotel/voyageurs'
    | '/login/$slug'
    | '/settings/catalogue'
    | '/settings/users'
    | '/super-admin/ia-platform'
    | '/super-admin/modules'
    | '/super-admin/partners'
    | '/super-admin/users'
    | '/app/'
    | '/hotel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/abonnement-expire'
    | '/achats'
    | '/categories'
    | '/clients'
    | '/demande-en-attente'
    | '/demo'
    | '/depenses'
    | '/devis'
    | '/essai-gratuit'
    | '/fonctionnalites'
    | '/forgot-password'
    | '/fournisseurs'
    | '/journal'
    | '/licence'
    | '/login'
    | '/parametres'
    | '/partner'
    | '/partner-admin'
    | '/partner-login'
    | '/rapports'
    | '/reset-password'
    | '/services'
    | '/stock'
    | '/super-admin'
    | '/tarifs'
    | '/utilisateurs'
    | '/ventes'
    | '/app/$'
    | '/app/assistant-ia'
    | '/hotel/calendrier'
    | '/hotel/chambres'
    | '/hotel/logements'
    | '/hotel/parametres'
    | '/hotel/prestataires'
    | '/hotel/rapports'
    | '/hotel/reservations'
    | '/hotel/sms'
    | '/hotel/voyageurs'
    | '/login/$slug'
    | '/settings/catalogue'
    | '/settings/users'
    | '/super-admin/ia-platform'
    | '/super-admin/modules'
    | '/super-admin/partners'
    | '/super-admin/users'
    | '/app'
    | '/hotel'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/abonnement-expire'
    | '/achats'
    | '/categories'
    | '/clients'
    | '/demande-en-attente'
    | '/demo'
    | '/depenses'
    | '/devis'
    | '/essai-gratuit'
    | '/fonctionnalites'
    | '/forgot-password'
    | '/fournisseurs'
    | '/hotel'
    | '/journal'
    | '/licence'
    | '/login'
    | '/parametres'
    | '/partner'
    | '/partner-admin'
    | '/partner-login'
    | '/rapports'
    | '/reset-password'
    | '/services'
    | '/stock'
    | '/super-admin'
    | '/tarifs'
    | '/utilisateurs'
    | '/ventes'
    | '/app/$'
    | '/app/assistant-ia'
    | '/hotel/calendrier'
    | '/hotel/chambres'
    | '/hotel/logements'
    | '/hotel/parametres'
    | '/hotel/prestataires'
    | '/hotel/rapports'
    | '/hotel/reservations'
    | '/hotel/sms'
    | '/hotel/voyageurs'
    | '/login_/$slug'
    | '/settings/catalogue'
    | '/settings/users'
    | '/super-admin/ia-platform'
    | '/super-admin/modules'
    | '/super-admin/partners'
    | '/super-admin/users'
    | '/app/'
    | '/hotel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AbonnementExpireRoute: typeof AbonnementExpireRoute
  AchatsRoute: typeof AchatsRoute
  CategoriesRoute: typeof CategoriesRoute
  ClientsRoute: typeof ClientsRoute
  DemandeEnAttenteRoute: typeof DemandeEnAttenteRoute
  DemoRoute: typeof DemoRoute
  DepensesRoute: typeof DepensesRoute
  DevisRoute: typeof DevisRoute
  EssaiGratuitRoute: typeof EssaiGratuitRoute
  FonctionnalitesRoute: typeof FonctionnalitesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FournisseursRoute: typeof FournisseursRoute
  HotelRoute: typeof HotelRouteWithChildren
  JournalRoute: typeof JournalRoute
  LicenceRoute: typeof LicenceRoute
  LoginRoute: typeof LoginRoute
  ParametresRoute: typeof ParametresRoute
  PartnerRoute: typeof PartnerRoute
  PartnerAdminRoute: typeof PartnerAdminRoute
  PartnerLoginRoute: typeof PartnerLoginRoute
  RapportsRoute: typeof RapportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  StockRoute: typeof StockRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  TarifsRoute: typeof TarifsRoute
  UtilisateursRoute: typeof UtilisateursRoute
  VentesRoute: typeof VentesRoute
  AppSplatRoute: typeof AppSplatRoute
  AppAssistantIaRoute: typeof AppAssistantIaRoute
  LoginSlugRoute: typeof LoginSlugRoute
  SettingsCatalogueRoute: typeof SettingsCatalogueRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement-expire': {
      id: '/abonnement-expire'
      path: '/abonnement-expire'
      fullPath: '/abonnement-expire'
      preLoaderRoute: typeof AbonnementExpireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achats': {
      id: '/achats'
      path: '/achats'
      fullPath: '/achats'
      preLoaderRoute: typeof AchatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demande-en-attente': {
      id: '/demande-en-attente'
      path: '/demande-en-attente'
      fullPath: '/demande-en-attente'
      preLoaderRoute: typeof DemandeEnAttenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essai-gratuit': {
      id: '/essai-gratuit'
      path: '/essai-gratuit'
      fullPath: '/essai-gratuit'
      preLoaderRoute: typeof EssaiGratuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licence': {
      id: '/licence'
      path: '/licence'
      fullPath: '/licence'
      preLoaderRoute: typeof LicenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-admin': {
      id: '/partner-admin'
      path: '/partner-admin'
      fullPath: '/partner-admin'
      preLoaderRoute: typeof PartnerAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-login': {
      id: '/partner-login'
      path: '/partner-login'
      fullPath: '/partner-login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventes': {
      id: '/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof VentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$': {
      id: '/app/$'
      path: '/app/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assistant-ia': {
      id: '/app/assistant-ia'
      path: '/app/assistant-ia'
      fullPath: '/app/assistant-ia'
      preLoaderRoute: typeof AppAssistantIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/': {
      id: '/hotel/'
      path: '/'
      fullPath: '/hotel/'
      preLoaderRoute: typeof HotelIndexRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/calendrier': {
      id: '/hotel/calendrier'
      path: '/calendrier'
      fullPath: '/hotel/calendrier'
      preLoaderRoute: typeof HotelCalendrierRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/chambres': {
      id: '/hotel/chambres'
      path: '/chambres'
      fullPath: '/hotel/chambres'
      preLoaderRoute: typeof HotelChambresRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/logements': {
      id: '/hotel/logements'
      path: '/logements'
      fullPath: '/hotel/logements'
      preLoaderRoute: typeof HotelLogementsRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/parametres': {
      id: '/hotel/parametres'
      path: '/parametres'
      fullPath: '/hotel/parametres'
      preLoaderRoute: typeof HotelParametresRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/prestataires': {
      id: '/hotel/prestataires'
      path: '/prestataires'
      fullPath: '/hotel/prestataires'
      preLoaderRoute: typeof HotelPrestatairesRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/rapports': {
      id: '/hotel/rapports'
      path: '/rapports'
      fullPath: '/hotel/rapports'
      preLoaderRoute: typeof HotelRapportsRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/reservations': {
      id: '/hotel/reservations'
      path: '/reservations'
      fullPath: '/hotel/reservations'
      preLoaderRoute: typeof HotelReservationsRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/sms': {
      id: '/hotel/sms'
      path: '/sms'
      fullPath: '/hotel/sms'
      preLoaderRoute: typeof HotelSmsRouteImport
      parentRoute: typeof HotelRoute
    }
    '/hotel/voyageurs': {
      id: '/hotel/voyageurs'
      path: '/voyageurs'
      fullPath: '/hotel/voyageurs'
      preLoaderRoute: typeof HotelVoyageursRouteImport
      parentRoute: typeof HotelRoute
    }
    '/login_/$slug': {
      id: '/login_/$slug'
      path: '/login/$slug'
      fullPath: '/login/$slug'
      preLoaderRoute: typeof LoginSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/catalogue': {
      id: '/settings/catalogue'
      path: '/settings/catalogue'
      fullPath: '/settings/catalogue'
      preLoaderRoute: typeof SettingsCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/ia-platform': {
      id: '/super-admin/ia-platform'
      path: '/ia-platform'
      fullPath: '/super-admin/ia-platform'
      preLoaderRoute: typeof SuperAdminIaPlatformRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/modules': {
      id: '/super-admin/modules'
      path: '/modules'
      fullPath: '/super-admin/modules'
      preLoaderRoute: typeof SuperAdminModulesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/partners': {
      id: '/super-admin/partners'
      path: '/partners'
      fullPath: '/super-admin/partners'
      preLoaderRoute: typeof SuperAdminPartnersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface HotelRouteChildren {
  HotelCalendrierRoute: typeof HotelCalendrierRoute
  HotelChambresRoute: typeof HotelChambresRoute
  HotelLogementsRoute: typeof HotelLogementsRoute
  HotelParametresRoute: typeof HotelParametresRoute
  HotelPrestatairesRoute: typeof HotelPrestatairesRoute
  HotelRapportsRoute: typeof HotelRapportsRoute
  HotelReservationsRoute: typeof HotelReservationsRoute
  HotelSmsRoute: typeof HotelSmsRoute
  HotelVoyageursRoute: typeof HotelVoyageursRoute
  HotelIndexRoute: typeof HotelIndexRoute
}

const HotelRouteChildren: HotelRouteChildren = {
  HotelCalendrierRoute: HotelCalendrierRoute,
  HotelChambresRoute: HotelChambresRoute,
  HotelLogementsRoute: HotelLogementsRoute,
  HotelParametresRoute: HotelParametresRoute,
  HotelPrestatairesRoute: HotelPrestatairesRoute,
  HotelRapportsRoute: HotelRapportsRoute,
  HotelReservationsRoute: HotelReservationsRoute,
  HotelSmsRoute: HotelSmsRoute,
  HotelVoyageursRoute: HotelVoyageursRoute,
  HotelIndexRoute: HotelIndexRoute,
}

const HotelRouteWithChildren = HotelRoute._addFileChildren(HotelRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminIaPlatformRoute: typeof SuperAdminIaPlatformRoute
  SuperAdminModulesRoute: typeof SuperAdminModulesRoute
  SuperAdminPartnersRoute: typeof SuperAdminPartnersRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminIaPlatformRoute: SuperAdminIaPlatformRoute,
  SuperAdminModulesRoute: SuperAdminModulesRoute,
  SuperAdminPartnersRoute: SuperAdminPartnersRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AbonnementExpireRoute: AbonnementExpireRoute,
  AchatsRoute: AchatsRoute,
  CategoriesRoute: CategoriesRoute,
  ClientsRoute: ClientsRoute,
  DemandeEnAttenteRoute: DemandeEnAttenteRoute,
  DemoRoute: DemoRoute,
  DepensesRoute: DepensesRoute,
  DevisRoute: DevisRoute,
  EssaiGratuitRoute: EssaiGratuitRoute,
  FonctionnalitesRoute: FonctionnalitesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FournisseursRoute: FournisseursRoute,
  HotelRoute: HotelRouteWithChildren,
  JournalRoute: JournalRoute,
  LicenceRoute: LicenceRoute,
  LoginRoute: LoginRoute,
  ParametresRoute: ParametresRoute,
  PartnerRoute: PartnerRoute,
  PartnerAdminRoute: PartnerAdminRoute,
  PartnerLoginRoute: PartnerLoginRoute,
  RapportsRoute: RapportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  StockRoute: StockRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  TarifsRoute: TarifsRoute,
  UtilisateursRoute: UtilisateursRoute,
  VentesRoute: VentesRoute,
  AppSplatRoute: AppSplatRoute,
  AppAssistantIaRoute: AppAssistantIaRoute,
  LoginSlugRoute: LoginSlugRoute,
  SettingsCatalogueRoute: SettingsCatalogueRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
