/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentesRouteImport } from './routes/ventes'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as StockRouteImport } from './routes/stock'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as PreviewAchatsRouteImport } from './routes/preview-achats'
import { Route as PartnerLoginRouteImport } from './routes/partner-login'
import { Route as PartnerAdminRouteImport } from './routes/partner-admin'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicenceRouteImport } from './routes/licence'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as EssaiGratuitRouteImport } from './routes/essai-gratuit'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AchatsRouteImport } from './routes/achats'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelIndexRouteImport } from './routes/hotel.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminSupportRouteImport } from './routes/super-admin.support'
import { Route as SuperAdminPartnersRouteImport } from './routes/super-admin.partners'
import { Route as SuperAdminIaPlatformRouteImport } from './routes/super-admin.ia-platform'
import { Route as SuperAdminAnalyticsRouteImport } from './routes/super-admin.analytics'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsCatalogueRouteImport } from './routes/settings.catalogue'
import { Route as LoginSlugRouteImport } from './routes/login_.$slug'
import { Route as HotelStocksRouteImport } from './routes/hotel.stocks'
import { Route as HotelRestaurantBarRouteImport } from './routes/hotel.restaurant-bar'
import { Route as HotelReservationsRouteImport } from './routes/hotel.reservations'
import { Route as HotelRapportsRouteImport } from './routes/hotel.rapports'
import { Route as HotelPersonnelRouteImport } from './routes/hotel.personnel'
import { Route as HotelParametresRouteImport } from './routes/hotel.parametres'
import { Route as HotelMaintenanceRouteImport } from './routes/hotel.maintenance'
import { Route as HotelHousekeepingRouteImport } from './routes/hotel.housekeeping'
import { Route as HotelFacturationRouteImport } from './routes/hotel.facturation'
import { Route as HotelDepensesRouteImport } from './routes/hotel.depenses'
import { Route as HotelComptabiliteRouteImport } from './routes/hotel.comptabilite'
import { Route as HotelClientsRouteImport } from './routes/hotel.clients'
import { Route as HotelCheckinCheckoutRouteImport } from './routes/hotel.checkin-checkout'
import { Route as HotelChambresRouteImport } from './routes/hotel.chambres'
import { Route as HotelCaisseRouteImport } from './routes/hotel.caisse'
import { Route as AppAssistantIaRouteImport } from './routes/app.assistant-ia'
import { Route as AppSplatRouteImport } from './routes/app.$'

const VentesRoute = VentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewAchatsRoute = PreviewAchatsRouteImport.update({
  id: '/preview-achats',
  path: '/preview-achats',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/partner-login',
  path: '/partner-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAdminRoute = PartnerAdminRouteImport.update({
  id: '/partner-admin',
  path: '/partner-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenceRoute = LicenceRouteImport.update({
  id: '/licence',
  path: '/licence',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaiGratuitRoute = EssaiGratuitRouteImport.update({
  id: '/essai-gratuit',
  path: '/essai-gratuit',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AchatsRoute = AchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelIndexRoute = HotelIndexRouteImport.update({
  id: '/hotel/',
  path: '/hotel/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSupportRoute = SuperAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPartnersRoute = SuperAdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminIaPlatformRoute = SuperAdminIaPlatformRouteImport.update({
  id: '/ia-platform',
  path: '/ia-platform',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAnalyticsRoute = SuperAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCatalogueRoute = SettingsCatalogueRouteImport.update({
  id: '/settings/catalogue',
  path: '/settings/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSlugRoute = LoginSlugRouteImport.update({
  id: '/login_/$slug',
  path: '/login/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelStocksRoute = HotelStocksRouteImport.update({
  id: '/hotel/stocks',
  path: '/hotel/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRestaurantBarRoute = HotelRestaurantBarRouteImport.update({
  id: '/hotel/restaurant-bar',
  path: '/hotel/restaurant-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelReservationsRoute = HotelReservationsRouteImport.update({
  id: '/hotel/reservations',
  path: '/hotel/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRapportsRoute = HotelRapportsRouteImport.update({
  id: '/hotel/rapports',
  path: '/hotel/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelPersonnelRoute = HotelPersonnelRouteImport.update({
  id: '/hotel/personnel',
  path: '/hotel/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelParametresRoute = HotelParametresRouteImport.update({
  id: '/hotel/parametres',
  path: '/hotel/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelMaintenanceRoute = HotelMaintenanceRouteImport.update({
  id: '/hotel/maintenance',
  path: '/hotel/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelHousekeepingRoute = HotelHousekeepingRouteImport.update({
  id: '/hotel/housekeeping',
  path: '/hotel/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelFacturationRoute = HotelFacturationRouteImport.update({
  id: '/hotel/facturation',
  path: '/hotel/facturation',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelDepensesRoute = HotelDepensesRouteImport.update({
  id: '/hotel/depenses',
  path: '/hotel/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelComptabiliteRoute = HotelComptabiliteRouteImport.update({
  id: '/hotel/comptabilite',
  path: '/hotel/comptabilite',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelClientsRoute = HotelClientsRouteImport.update({
  id: '/hotel/clients',
  path: '/hotel/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelCheckinCheckoutRoute = HotelCheckinCheckoutRouteImport.update({
  id: '/hotel/checkin-checkout',
  path: '/hotel/checkin-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelChambresRoute = HotelChambresRouteImport.update({
  id: '/hotel/chambres',
  path: '/hotel/chambres',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelCaisseRoute = HotelCaisseRouteImport.update({
  id: '/hotel/caisse',
  path: '/hotel/caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssistantIaRoute = AppAssistantIaRouteImport.update({
  id: '/app/assistant-ia',
  path: '/app/assistant-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/app/$',
  path: '/app/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/achats': typeof AchatsRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/demo': typeof DemoRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/essai-gratuit': typeof EssaiGratuitRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fournisseurs': typeof FournisseursRoute
  '/journal': typeof JournalRoute
  '/licence': typeof LicenceRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/partner': typeof PartnerRoute
  '/partner-admin': typeof PartnerAdminRoute
  '/partner-login': typeof PartnerLoginRoute
  '/preview-achats': typeof PreviewAchatsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/stock': typeof StockRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/support': typeof SupportRoute
  '/tarifs': typeof TarifsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
  '/app/$': typeof AppSplatRoute
  '/app/assistant-ia': typeof AppAssistantIaRoute
  '/hotel/caisse': typeof HotelCaisseRoute
  '/hotel/chambres': typeof HotelChambresRoute
  '/hotel/checkin-checkout': typeof HotelCheckinCheckoutRoute
  '/hotel/clients': typeof HotelClientsRoute
  '/hotel/comptabilite': typeof HotelComptabiliteRoute
  '/hotel/depenses': typeof HotelDepensesRoute
  '/hotel/facturation': typeof HotelFacturationRoute
  '/hotel/housekeeping': typeof HotelHousekeepingRoute
  '/hotel/maintenance': typeof HotelMaintenanceRoute
  '/hotel/parametres': typeof HotelParametresRoute
  '/hotel/personnel': typeof HotelPersonnelRoute
  '/hotel/rapports': typeof HotelRapportsRoute
  '/hotel/reservations': typeof HotelReservationsRoute
  '/hotel/restaurant-bar': typeof HotelRestaurantBarRoute
  '/hotel/stocks': typeof HotelStocksRoute
  '/login/$slug': typeof LoginSlugRoute
  '/settings/catalogue': typeof SettingsCatalogueRoute
  '/settings/users': typeof SettingsUsersRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/ia-platform': typeof SuperAdminIaPlatformRoute
  '/super-admin/partners': typeof SuperAdminPartnersRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/app/': typeof AppIndexRoute
  '/hotel/': typeof HotelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/achats': typeof AchatsRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/demo': typeof DemoRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/essai-gratuit': typeof EssaiGratuitRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fournisseurs': typeof FournisseursRoute
  '/journal': typeof JournalRoute
  '/licence': typeof LicenceRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/partner': typeof PartnerRoute
  '/partner-admin': typeof PartnerAdminRoute
  '/partner-login': typeof PartnerLoginRoute
  '/preview-achats': typeof PreviewAchatsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/stock': typeof StockRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/support': typeof SupportRoute
  '/tarifs': typeof TarifsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
  '/app/$': typeof AppSplatRoute
  '/app/assistant-ia': typeof AppAssistantIaRoute
  '/hotel/caisse': typeof HotelCaisseRoute
  '/hotel/chambres': typeof HotelChambresRoute
  '/hotel/checkin-checkout': typeof HotelCheckinCheckoutRoute
  '/hotel/clients': typeof HotelClientsRoute
  '/hotel/comptabilite': typeof HotelComptabiliteRoute
  '/hotel/depenses': typeof HotelDepensesRoute
  '/hotel/facturation': typeof HotelFacturationRoute
  '/hotel/housekeeping': typeof HotelHousekeepingRoute
  '/hotel/maintenance': typeof HotelMaintenanceRoute
  '/hotel/parametres': typeof HotelParametresRoute
  '/hotel/personnel': typeof HotelPersonnelRoute
  '/hotel/rapports': typeof HotelRapportsRoute
  '/hotel/reservations': typeof HotelReservationsRoute
  '/hotel/restaurant-bar': typeof HotelRestaurantBarRoute
  '/hotel/stocks': typeof HotelStocksRoute
  '/login/$slug': typeof LoginSlugRoute
  '/settings/catalogue': typeof SettingsCatalogueRoute
  '/settings/users': typeof SettingsUsersRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/ia-platform': typeof SuperAdminIaPlatformRoute
  '/super-admin/partners': typeof SuperAdminPartnersRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/app': typeof AppIndexRoute
  '/hotel': typeof HotelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/achats': typeof AchatsRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/demo': typeof DemoRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/essai-gratuit': typeof EssaiGratuitRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fournisseurs': typeof FournisseursRoute
  '/journal': typeof JournalRoute
  '/licence': typeof LicenceRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/partner': typeof PartnerRoute
  '/partner-admin': typeof PartnerAdminRoute
  '/partner-login': typeof PartnerLoginRoute
  '/preview-achats': typeof PreviewAchatsRoute
  '/rapports': typeof RapportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/stock': typeof StockRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/support': typeof SupportRoute
  '/tarifs': typeof TarifsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
  '/app/$': typeof AppSplatRoute
  '/app/assistant-ia': typeof AppAssistantIaRoute
  '/hotel/caisse': typeof HotelCaisseRoute
  '/hotel/chambres': typeof HotelChambresRoute
  '/hotel/checkin-checkout': typeof HotelCheckinCheckoutRoute
  '/hotel/clients': typeof HotelClientsRoute
  '/hotel/comptabilite': typeof HotelComptabiliteRoute
  '/hotel/depenses': typeof HotelDepensesRoute
  '/hotel/facturation': typeof HotelFacturationRoute
  '/hotel/housekeeping': typeof HotelHousekeepingRoute
  '/hotel/maintenance': typeof HotelMaintenanceRoute
  '/hotel/parametres': typeof HotelParametresRoute
  '/hotel/personnel': typeof HotelPersonnelRoute
  '/hotel/rapports': typeof HotelRapportsRoute
  '/hotel/reservations': typeof HotelReservationsRoute
  '/hotel/restaurant-bar': typeof HotelRestaurantBarRoute
  '/hotel/stocks': typeof HotelStocksRoute
  '/login_/$slug': typeof LoginSlugRoute
  '/settings/catalogue': typeof SettingsCatalogueRoute
  '/settings/users': typeof SettingsUsersRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/ia-platform': typeof SuperAdminIaPlatformRoute
  '/super-admin/partners': typeof SuperAdminPartnersRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/app/': typeof AppIndexRoute
  '/hotel/': typeof HotelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/achats'
    | '/categories'
    | '/clients'
    | '/demo'
    | '/depenses'
    | '/devis'
    | '/essai-gratuit'
    | '/fonctionnalites'
    | '/forgot-password'
    | '/fournisseurs'
    | '/journal'
    | '/licence'
    | '/login'
    | '/parametres'
    | '/partner'
    | '/partner-admin'
    | '/partner-login'
    | '/preview-achats'
    | '/rapports'
    | '/reset-password'
    | '/services'
    | '/stock'
    | '/super-admin'
    | '/support'
    | '/tarifs'
    | '/utilisateurs'
    | '/ventes'
    | '/app/$'
    | '/app/assistant-ia'
    | '/hotel/caisse'
    | '/hotel/chambres'
    | '/hotel/checkin-checkout'
    | '/hotel/clients'
    | '/hotel/comptabilite'
    | '/hotel/depenses'
    | '/hotel/facturation'
    | '/hotel/housekeeping'
    | '/hotel/maintenance'
    | '/hotel/parametres'
    | '/hotel/personnel'
    | '/hotel/rapports'
    | '/hotel/reservations'
    | '/hotel/restaurant-bar'
    | '/hotel/stocks'
    | '/login/$slug'
    | '/settings/catalogue'
    | '/settings/users'
    | '/super-admin/analytics'
    | '/super-admin/ia-platform'
    | '/super-admin/partners'
    | '/super-admin/support'
    | '/super-admin/users'
    | '/app/'
    | '/hotel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/achats'
    | '/categories'
    | '/clients'
    | '/demo'
    | '/depenses'
    | '/devis'
    | '/essai-gratuit'
    | '/fonctionnalites'
    | '/forgot-password'
    | '/fournisseurs'
    | '/journal'
    | '/licence'
    | '/login'
    | '/parametres'
    | '/partner'
    | '/partner-admin'
    | '/partner-login'
    | '/preview-achats'
    | '/rapports'
    | '/reset-password'
    | '/services'
    | '/stock'
    | '/super-admin'
    | '/support'
    | '/tarifs'
    | '/utilisateurs'
    | '/ventes'
    | '/app/$'
    | '/app/assistant-ia'
    | '/hotel/caisse'
    | '/hotel/chambres'
    | '/hotel/checkin-checkout'
    | '/hotel/clients'
    | '/hotel/comptabilite'
    | '/hotel/depenses'
    | '/hotel/facturation'
    | '/hotel/housekeeping'
    | '/hotel/maintenance'
    | '/hotel/parametres'
    | '/hotel/personnel'
    | '/hotel/rapports'
    | '/hotel/reservations'
    | '/hotel/restaurant-bar'
    | '/hotel/stocks'
    | '/login/$slug'
    | '/settings/catalogue'
    | '/settings/users'
    | '/super-admin/analytics'
    | '/super-admin/ia-platform'
    | '/super-admin/partners'
    | '/super-admin/support'
    | '/super-admin/users'
    | '/app'
    | '/hotel'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/achats'
    | '/categories'
    | '/clients'
    | '/demo'
    | '/depenses'
    | '/devis'
    | '/essai-gratuit'
    | '/fonctionnalites'
    | '/forgot-password'
    | '/fournisseurs'
    | '/journal'
    | '/licence'
    | '/login'
    | '/parametres'
    | '/partner'
    | '/partner-admin'
    | '/partner-login'
    | '/preview-achats'
    | '/rapports'
    | '/reset-password'
    | '/services'
    | '/stock'
    | '/super-admin'
    | '/support'
    | '/tarifs'
    | '/utilisateurs'
    | '/ventes'
    | '/app/$'
    | '/app/assistant-ia'
    | '/hotel/caisse'
    | '/hotel/chambres'
    | '/hotel/checkin-checkout'
    | '/hotel/clients'
    | '/hotel/comptabilite'
    | '/hotel/depenses'
    | '/hotel/facturation'
    | '/hotel/housekeeping'
    | '/hotel/maintenance'
    | '/hotel/parametres'
    | '/hotel/personnel'
    | '/hotel/rapports'
    | '/hotel/reservations'
    | '/hotel/restaurant-bar'
    | '/hotel/stocks'
    | '/login_/$slug'
    | '/settings/catalogue'
    | '/settings/users'
    | '/super-admin/analytics'
    | '/super-admin/ia-platform'
    | '/super-admin/partners'
    | '/super-admin/support'
    | '/super-admin/users'
    | '/app/'
    | '/hotel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AchatsRoute: typeof AchatsRoute
  CategoriesRoute: typeof CategoriesRoute
  ClientsRoute: typeof ClientsRoute
  DemoRoute: typeof DemoRoute
  DepensesRoute: typeof DepensesRoute
  DevisRoute: typeof DevisRoute
  EssaiGratuitRoute: typeof EssaiGratuitRoute
  FonctionnalitesRoute: typeof FonctionnalitesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FournisseursRoute: typeof FournisseursRoute
  JournalRoute: typeof JournalRoute
  LicenceRoute: typeof LicenceRoute
  LoginRoute: typeof LoginRoute
  ParametresRoute: typeof ParametresRoute
  PartnerRoute: typeof PartnerRoute
  PartnerAdminRoute: typeof PartnerAdminRoute
  PartnerLoginRoute: typeof PartnerLoginRoute
  PreviewAchatsRoute: typeof PreviewAchatsRoute
  RapportsRoute: typeof RapportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  StockRoute: typeof StockRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  SupportRoute: typeof SupportRoute
  TarifsRoute: typeof TarifsRoute
  UtilisateursRoute: typeof UtilisateursRoute
  VentesRoute: typeof VentesRoute
  AppSplatRoute: typeof AppSplatRoute
  AppAssistantIaRoute: typeof AppAssistantIaRoute
  HotelCaisseRoute: typeof HotelCaisseRoute
  HotelChambresRoute: typeof HotelChambresRoute
  HotelCheckinCheckoutRoute: typeof HotelCheckinCheckoutRoute
  HotelClientsRoute: typeof HotelClientsRoute
  HotelComptabiliteRoute: typeof HotelComptabiliteRoute
  HotelDepensesRoute: typeof HotelDepensesRoute
  HotelFacturationRoute: typeof HotelFacturationRoute
  HotelHousekeepingRoute: typeof HotelHousekeepingRoute
  HotelMaintenanceRoute: typeof HotelMaintenanceRoute
  HotelParametresRoute: typeof HotelParametresRoute
  HotelPersonnelRoute: typeof HotelPersonnelRoute
  HotelRapportsRoute: typeof HotelRapportsRoute
  HotelReservationsRoute: typeof HotelReservationsRoute
  HotelRestaurantBarRoute: typeof HotelRestaurantBarRoute
  HotelStocksRoute: typeof HotelStocksRoute
  LoginSlugRoute: typeof LoginSlugRoute
  SettingsCatalogueRoute: typeof SettingsCatalogueRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  HotelIndexRoute: typeof HotelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventes': {
      id: '/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof VentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-achats': {
      id: '/preview-achats'
      path: '/preview-achats'
      fullPath: '/preview-achats'
      preLoaderRoute: typeof PreviewAchatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-login': {
      id: '/partner-login'
      path: '/partner-login'
      fullPath: '/partner-login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-admin': {
      id: '/partner-admin'
      path: '/partner-admin'
      fullPath: '/partner-admin'
      preLoaderRoute: typeof PartnerAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licence': {
      id: '/licence'
      path: '/licence'
      fullPath: '/licence'
      preLoaderRoute: typeof LicenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essai-gratuit': {
      id: '/essai-gratuit'
      path: '/essai-gratuit'
      fullPath: '/essai-gratuit'
      preLoaderRoute: typeof EssaiGratuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achats': {
      id: '/achats'
      path: '/achats'
      fullPath: '/achats'
      preLoaderRoute: typeof AchatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/': {
      id: '/hotel/'
      path: '/hotel'
      fullPath: '/hotel/'
      preLoaderRoute: typeof HotelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/support': {
      id: '/super-admin/support'
      path: '/support'
      fullPath: '/super-admin/support'
      preLoaderRoute: typeof SuperAdminSupportRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/partners': {
      id: '/super-admin/partners'
      path: '/partners'
      fullPath: '/super-admin/partners'
      preLoaderRoute: typeof SuperAdminPartnersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/ia-platform': {
      id: '/super-admin/ia-platform'
      path: '/ia-platform'
      fullPath: '/super-admin/ia-platform'
      preLoaderRoute: typeof SuperAdminIaPlatformRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/analytics': {
      id: '/super-admin/analytics'
      path: '/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof SuperAdminAnalyticsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/catalogue': {
      id: '/settings/catalogue'
      path: '/settings/catalogue'
      fullPath: '/settings/catalogue'
      preLoaderRoute: typeof SettingsCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/$slug': {
      id: '/login_/$slug'
      path: '/login/$slug'
      fullPath: '/login/$slug'
      preLoaderRoute: typeof LoginSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/stocks': {
      id: '/hotel/stocks'
      path: '/hotel/stocks'
      fullPath: '/hotel/stocks'
      preLoaderRoute: typeof HotelStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/restaurant-bar': {
      id: '/hotel/restaurant-bar'
      path: '/hotel/restaurant-bar'
      fullPath: '/hotel/restaurant-bar'
      preLoaderRoute: typeof HotelRestaurantBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/reservations': {
      id: '/hotel/reservations'
      path: '/hotel/reservations'
      fullPath: '/hotel/reservations'
      preLoaderRoute: typeof HotelReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/rapports': {
      id: '/hotel/rapports'
      path: '/hotel/rapports'
      fullPath: '/hotel/rapports'
      preLoaderRoute: typeof HotelRapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/personnel': {
      id: '/hotel/personnel'
      path: '/hotel/personnel'
      fullPath: '/hotel/personnel'
      preLoaderRoute: typeof HotelPersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/parametres': {
      id: '/hotel/parametres'
      path: '/hotel/parametres'
      fullPath: '/hotel/parametres'
      preLoaderRoute: typeof HotelParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/maintenance': {
      id: '/hotel/maintenance'
      path: '/hotel/maintenance'
      fullPath: '/hotel/maintenance'
      preLoaderRoute: typeof HotelMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/housekeeping': {
      id: '/hotel/housekeeping'
      path: '/hotel/housekeeping'
      fullPath: '/hotel/housekeeping'
      preLoaderRoute: typeof HotelHousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/facturation': {
      id: '/hotel/facturation'
      path: '/hotel/facturation'
      fullPath: '/hotel/facturation'
      preLoaderRoute: typeof HotelFacturationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/depenses': {
      id: '/hotel/depenses'
      path: '/hotel/depenses'
      fullPath: '/hotel/depenses'
      preLoaderRoute: typeof HotelDepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/comptabilite': {
      id: '/hotel/comptabilite'
      path: '/hotel/comptabilite'
      fullPath: '/hotel/comptabilite'
      preLoaderRoute: typeof HotelComptabiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/clients': {
      id: '/hotel/clients'
      path: '/hotel/clients'
      fullPath: '/hotel/clients'
      preLoaderRoute: typeof HotelClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/checkin-checkout': {
      id: '/hotel/checkin-checkout'
      path: '/hotel/checkin-checkout'
      fullPath: '/hotel/checkin-checkout'
      preLoaderRoute: typeof HotelCheckinCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/chambres': {
      id: '/hotel/chambres'
      path: '/hotel/chambres'
      fullPath: '/hotel/chambres'
      preLoaderRoute: typeof HotelChambresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/caisse': {
      id: '/hotel/caisse'
      path: '/hotel/caisse'
      fullPath: '/hotel/caisse'
      preLoaderRoute: typeof HotelCaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assistant-ia': {
      id: '/app/assistant-ia'
      path: '/app/assistant-ia'
      fullPath: '/app/assistant-ia'
      preLoaderRoute: typeof AppAssistantIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$': {
      id: '/app/$'
      path: '/app/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperAdminRouteChildren {
  SuperAdminAnalyticsRoute: typeof SuperAdminAnalyticsRoute
  SuperAdminIaPlatformRoute: typeof SuperAdminIaPlatformRoute
  SuperAdminPartnersRoute: typeof SuperAdminPartnersRoute
  SuperAdminSupportRoute: typeof SuperAdminSupportRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAnalyticsRoute: SuperAdminAnalyticsRoute,
  SuperAdminIaPlatformRoute: SuperAdminIaPlatformRoute,
  SuperAdminPartnersRoute: SuperAdminPartnersRoute,
  SuperAdminSupportRoute: SuperAdminSupportRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AchatsRoute: AchatsRoute,
  CategoriesRoute: CategoriesRoute,
  ClientsRoute: ClientsRoute,
  DemoRoute: DemoRoute,
  DepensesRoute: DepensesRoute,
  DevisRoute: DevisRoute,
  EssaiGratuitRoute: EssaiGratuitRoute,
  FonctionnalitesRoute: FonctionnalitesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FournisseursRoute: FournisseursRoute,
  JournalRoute: JournalRoute,
  LicenceRoute: LicenceRoute,
  LoginRoute: LoginRoute,
  ParametresRoute: ParametresRoute,
  PartnerRoute: PartnerRoute,
  PartnerAdminRoute: PartnerAdminRoute,
  PartnerLoginRoute: PartnerLoginRoute,
  PreviewAchatsRoute: PreviewAchatsRoute,
  RapportsRoute: RapportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  StockRoute: StockRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  SupportRoute: SupportRoute,
  TarifsRoute: TarifsRoute,
  UtilisateursRoute: UtilisateursRoute,
  VentesRoute: VentesRoute,
  AppSplatRoute: AppSplatRoute,
  AppAssistantIaRoute: AppAssistantIaRoute,
  HotelCaisseRoute: HotelCaisseRoute,
  HotelChambresRoute: HotelChambresRoute,
  HotelCheckinCheckoutRoute: HotelCheckinCheckoutRoute,
  HotelClientsRoute: HotelClientsRoute,
  HotelComptabiliteRoute: HotelComptabiliteRoute,
  HotelDepensesRoute: HotelDepensesRoute,
  HotelFacturationRoute: HotelFacturationRoute,
  HotelHousekeepingRoute: HotelHousekeepingRoute,
  HotelMaintenanceRoute: HotelMaintenanceRoute,
  HotelParametresRoute: HotelParametresRoute,
  HotelPersonnelRoute: HotelPersonnelRoute,
  HotelRapportsRoute: HotelRapportsRoute,
  HotelReservationsRoute: HotelReservationsRoute,
  HotelRestaurantBarRoute: HotelRestaurantBarRoute,
  HotelStocksRoute: HotelStocksRoute,
  LoginSlugRoute: LoginSlugRoute,
  SettingsCatalogueRoute: SettingsCatalogueRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  AppIndexRoute: AppIndexRoute,
  HotelIndexRoute: HotelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
