// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    // No local session is the normal state for public/anonymous server functions
    // (e.g. the trial signup RPC). Do not treat that as an expired session here —
    // protected server functions enforce their own auth via `requireSupabaseAuth`
    // and return 401, which `fetchServerFnWithAuthRetry` already turns into the
    // real "session expired" redirect after a failed refresh attempt.
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    if (!token) return next();
    return next({
      headers: { Authorization: `Bearer ${token}` },
    });
  },
);
