// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data, error } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    if (error || !token) {
      sessionStorage.setItem("mms:auth-message", "Votre session a expiré. Veuillez vous reconnecter.");
      await supabase.auth.signOut();
      window.location.assign("/login");
      throw new Error("Votre session a expiré. Veuillez vous reconnecter.");
    }
    return next({
      headers: { Authorization: `Bearer ${token}` },
    });
  },
);
